sudo: false
language: go
go_import_path: gopkg.in/gographics/imagick.v2
go:
 - 1.6
 #- 1.5
 #- 1.4
cache:
    directories:
        - $HOME/im
env:
    #- IMAGEMAGICK_VERSION=git7
    #- IMAGEMAGICK_VERSION=git6
    #- IMAGEMAGICK_VERSION=7.0.1-0
    - IMAGEMAGICK_VERSION=6.9.4-10
    # - IMAGEMAGICK_VERSION=6.8.7-0
    #- IMAGEMAGICK_VERSION=6.7.5-3
    #- IMAGEMAGICK_VERSION=6.6.0-9
    #- IMAGEMAGICK_VERSION=6.5.3-10
    # Include individual commits like this:
    # - IMAGEMAGICK_VERSION=commit_25553302a6d5f736b55e60109600dfbce5fbea48

#matrix:
#  exclude:
#    - php: 5.3
#      env: IMAGEMAGICK_VERSION=6.8.7-0
before_install:
    - bash ./imagemagick_dependency.sh "${IMAGEMAGICK_VERSION}"
    - echo "ImageMagick version - ${IMAGEMAGICK_VERSION}"
    - convert --version
    - export PKG_CONFIG_PATH="/home/travis/im/imagemagick-${IMAGEMAGICK_VERSION}/lib/pkgconfig:${PKG_CONFIG_PATH}"
    - echo "PKG_CONFIG_DIR ${PKG_CONFIG_DIR}"
    - pkg-config --cflags --libs MagickWand
    



# debugging why this is borked.
install:
    - convert --version


before_script:
    - pwd
    - ls -l /home/travis/gopath
    - ls -l /home/travis/gopath/src
    - for i in $GOPATH/src/gopkg.in/gographics/imagick.v2/imagick/*.go; do  echo "checking ${i}"; gofmt -l $i; echo $?; done
    - for i in $GOPATH/src/gopkg.in/gographics/imagick.v2/imagick/examples/*.go; do gofmt -l $i 2>/dev/null; echo $?; done

script:
    - cd $GOPATH/src/gopkg.in/gographics/imagick.v2/imagick/examples/morphology
    - ls -l
    - go build -tags no_pkgconfig -ldflags "-r /home/travis/im/imagemagick-${IMAGEMAGICK_VERSION}/lib" -v main.go
    - ./main
    - cd $GOPATH
    - go test -tags no_pkgconfig -ldflags "-r /home/travis/im/imagemagick-${IMAGEMAGICK_VERSION}/lib" -v ./...


matrix:
  allow_failures:
    - env: IMAGEMAGICK_VERSION=git6
    - env: IMAGEMAGICK_VERSION=git7
