sudo: false
language: go
install:

go:
 - 1.6
 - 1.5
 - 1.4

sudo: false
cache:
    directories:
        - $HOME/im

env:
    #- IMAGEMAGICK_VERSION=git7
    #- IMAGEMAGICK_VERSION=git6
    #- IMAGEMAGICK_VERSION=7.0.1-0
    - IMAGEMAGICK_VERSION=6.9.2-0
    - IMAGEMAGICK_VERSION=6.8.7-0
    #- IMAGEMAGICK_VERSION=6.7.5-3
    #- IMAGEMAGICK_VERSION=6.6.0-9
    #- IMAGEMAGICK_VERSION=6.5.3-10
    # Include individual commits like this:
    # - IMAGEMAGICK_VERSION=commit_25553302a6d5f736b55e60109600dfbce5fbea48

#matrix:
#  exclude:
#    - php: 5.3
#      env: IMAGEMAGICK_VERSION=6.8.7-0


#before_script:
#    - for file in tests/*.phpt; do grep $(basename $file) package.xml >/dev/null || (echo "Missing $file from package.xml" ; exit 1); done
    - bash ./imagemagick_dependency.sh "${IMAGEMAGICK_VERSION}"

script:
    - go get -t -v ./...
    - go test -v
    

matrix:
  allow_failures:
    - env: IMAGEMAGICK_VERSION=git6
    - env: IMAGEMAGICK_VERSION=git7
